## Assignment 1

Do Exercise 1.10 in *Learning from Data*.  The problem is restated below:

Write a program to flip 1000 fair coins.  Flip each coin 10 times, then select three coins as follows:

* select the first coin flipped ($c_1$)
* Select the first coin with the minimum number of heads ($c_{min}$)
* Select another coin completely at random ($c_{rand}$)

Let $\nu_1,\ \nu_{min},\ \nu_{rand}$ be the fraction of heads for the three selected coins.  Let $\mu$ be the actual probability of heads.

a.  What is $\mu$ for the coins?

b.  repeat the experiment a great number of times (e.g., 100,000 times).  collect $\nu_1,\ \nu_{min},\ \nu_{rand}$ for each experiment.  Plot histograms of $\nu_1,\ \nu_{min},\ \nu_{rand}$ to see what the distribution looks like.  Note that the coin for $c_{rand}$ and $c_{min}$ will be probably different for each run.

c. plot the hoeffding bound $2 * e^{-2 \epsilon^2 N}$ along with the $P(| \nu-\mu | > \epsilon)$ for different values of epsilon.  $N$ is the number of training examples (10 in this case), and number of hypotheses is $M = 1000$.

d. Which coins obey Hoeffding bound?  which do not?  why?

e. Explain how the model described here compares to the bin model described in the book and the lecture.

In [4]:
import numpy as np
# Emulating a coin flip in python with numpy.
# here are a few possible approaches.  remember 
# that coin flips are independent.  That means 
# that we can generate all the flips sequentially.

M = 1000 # number of separate coins flipped
N = 10   # number of samples from each coin

# coin flipping is a binomial process with p = 0.5 for a fair coin
data = np.random.binomial(size=N*M, n=1, p=0.5)
print(data.shape)

data = data.reshape(1000,10)
print(data.shape)

(10000,)
(1000, 10)


In [7]:
print(data[:20, :])

[[0 0 1 1 0 0 1 0 0 1]
 [0 0 1 0 1 0 1 1 1 0]
 [0 1 1 0 1 1 0 0 1 1]
 [1 0 1 0 0 1 0 1 0 0]
 [0 0 0 1 1 0 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 1 0 1 1 1 1 0 1 1]
 [1 0 0 1 0 1 0 0 0 1]
 [1 1 0 0 1 1 0 0 1 1]
 [1 1 1 0 1 1 1 1 1 1]
 [0 1 1 1 1 0 1 1 0 0]
 [1 0 0 0 1 1 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 1 0 1 0 0 1 1 1 1]
 [1 0 0 0 0 1 1 1 1 0]
 [0 1 1 1 0 1 1 1 1 1]
 [0 1 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 1 1 1]
 [1 1 1 0 0 1 1 0 1 0]
 [1 0 0 1 0 0 0 0 0 0]]


What are the total number of heads for each coin? $(\nu_i)$?

In [11]:
np.sum(data, axis = 1)[:20]

array([4, 5, 6, 4, 4, 2, 7, 4, 6, 9, 6, 4, 1, 7, 5, 8, 4, 3, 6, 2])

How do I choose a random $c$ and $\nu_i$?

In [14]:
# use choice!  remember M=1000, the number of coins.  
# we need to choose one of them.  this function will return the index we want.
idx = np.random.choice(M) # choose a coin from the M coins uniformly.
print(idx)
print("c_rand is {} with nu_rand = {}".format(data[idx, :], np.sum(data[idx, :])))

710
c_rand is [0 0 1 0 1 1 0 0 0 1] with nu_rand = 4
